# Generated by Django 4.0.6 on 2022-08-15 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_user_listing_author_bids_bidder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='active',
            new_name='status',
        ),
    ]
