# Generated by Django 4.0.6 on 2022-08-26 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_bids_bidder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='current_bid',
        ),
    ]
